### ISSUE TITLE
Error setting up entry Peaqnext-sensors for peaqnext

### ISSUE THREAD

**Issue by Hoekeren** [elden1337/hass-peaqnext#30]
Denne fejl stammer fra en brugerdefineret integration.

Logger: homeassistant.config_entries
Source: custom_components/peaqnext/__init__.py:61
Integration: peaqnext, utility sensors (documentation, issues)
First occurred: 18. september 2023 kl. 22.51.51 (2 occurrences)
Last logged: 18. september 2023 kl. 22.51.51

Error setting up entry Peaqnext-sensors for peaqnext
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/peaqnext/__init__.py", line 28, in async_setup_entry
    internal_sensors = await async_create_internal_sensors(conf)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/peaqnext/__init__.py", line 61, in async_create_internal_sensors
    update_by=UpdateBy(s.get(CONF_UPDATE_BY)),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 712, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 1128, in __new__
    raise ve_exc
ValueError: None is not a valid UpdateBy

**Comment by elden1337** [comment]
try 0.5.5.

**Comment by Hoekeren** [comment]
The sensors now do not start after a restart of HA. I have to manually restart every sensor to get the started. Furthermore the sensors show optimal start time that lies before the present time?

Logger: homeassistant.config_entries
Source: helpers/event.py:198
First occurred: 08.01.25 (2 occurrences)
Last logged: 08.01.25

Error setting up entry Peaqnext-sensors for peaqnext
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/peaqnext/__init__.py", line 25, in async_setup_entry
    hub = Hub(hass)
          ^^^^^^^^^
  File "/config/custom_components/peaqnext/service/hub.py", line 29, in __init__
    async_track_state_change(
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 198, in async_track_state_change
    entity_ids = tuple(entity_id.lower() for entity_id in entity_ids)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 198, in <genexpr>
    entity_ids = tuple(entity_id.lower() for entity_id in entity_ids)
                       ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by elden1337** [comment]
very weird indeed...

**Comment by Hoekeren** [comment]
![Screenshot_2023-09-20-12-50-28-58_c3a231c25ed346e59462e84656a70e50](https://github.com/elden1337/hass-peaqnext/assets/33251946/d733682f-b9f6-4a44-84a8-a5783299a21d)

**Comment by elden1337** [comment]
thanks. can you open up one of them so that i can see the attributes for the sensor?

**Comment by Hoekeren** [comment]
![Screenshot_2023-09-20-14-10-24-55](https://github.com/elden1337/hass-peaqnext/assets/33251946/3d101851-2045-4f8f-bd9f-0cbf2dd53064)

**Comment by elden1337** [comment]
The part where it says 12:00 is because it's ser to hourly update and not every minute. 
The other errors still pending. Will see if i get time tonight to have a look there.
